name: alertsysapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  share_plus: ^10.1.0
  path_provider: ^2.1.5
  file_saver: ^0.2.0   # optional, but simplifies web saves
  universal_html: ^2.2.4
  onesignal_flutter: ^5.2.0
  flutter_local_notifications: ^18.0.1
  shorebird_code_push: ^1.0.0
  vibration: ^3.1.4
  google_generative_ai: ^0.4.3
  device_info_plus: ^11.0.0
  http: ^1.3.0
  csv: ^6.0.0
  excel: ^4.0.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_database: 12.1.3 

  # UI helpers
  google_fonts: ^6.3.0
  intl: ^0.20.2
  provider: ^6.1.2
flutter:
  assets:
    - shorebird.yaml
