// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyAr9G-E1G_HDf2DOBoUvoqfuCXBed8mPUM',
  appId: '1:284893821377:web:cc49bb5284b409e989d740',
  messagingSenderId: '284893821377',
  projectId: 'alertappsys',
  authDomain: 'alertappsys.firebaseapp.com',
  storageBucket: 'alertappsys.firebasestorage.app',
  databaseURL: 'https://alertappsys-default-rtdb.firebaseio.com', // ✅ fixed
);

static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyAEN8VNSnC2PNqEwJexY6mwEnMY3C6T_is',
  appId: '1:284893821377:android:8d898224d4b2914489d740',
  messagingSenderId: '284893821377',
  projectId: 'alertappsys',
  storageBucket: 'alertappsys.firebasestorage.app',
  databaseURL: 'https://alertappsys-default-rtdb.firebaseio.com', // ✅ added
);

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdI_K7YOma5phLkz0XhgyHUaXNfoXxR8c',
    appId: '1:284893821377:ios:0a01173e8cd7279289d740',
    messagingSenderId: '284893821377',
    projectId: 'alertappsys',
    storageBucket: 'alertappsys.firebasestorage.app',
    iosBundleId: 'com.example.alertsysapp',
    databaseURL: 'https://alertappsys-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdI_K7YOma5phLkz0XhgyHUaXNfoXxR8c',
    appId: '1:284893821377:ios:0a01173e8cd7279289d740',
    messagingSenderId: '284893821377',
    projectId: 'alertappsys',
    storageBucket: 'alertappsys.firebasestorage.app',
    iosBundleId: 'com.example.alertsysapp',
    databaseURL: 'https://alertappsys-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr9G-E1G_HDf2DOBoUvoqfuCXBed8mPUM',
    appId: '1:284893821377:web:eb1d515ff9ad7bab89d740',
    messagingSenderId: '284893821377',
    projectId: 'alertappsys',
    authDomain: 'alertappsys.firebaseapp.com',
    storageBucket: 'alertappsys.firebasestorage.app',
    databaseURL: 'https://alertappsys-default-rtdb.firebaseio.com',
  );
}
