#!/usr/bin/env node
// Builds the per-tenant worker secret bundle from the freshly-created Firebase
// runtime identity plus shared provisioning secrets. Values are never printed.

import { randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

export function escapeEnvValue(value) {
  return String(value ?? '').replaceAll('\r', '').replaceAll('\n', '');
}

export function buildTenantEnv({
  firebaseServiceAccount,
  firebaseApiKey,
  workerSharedSecret,
  githubToken,
  scimToken,
  alertWebhookUrl,
  ingestSharedSecret,
}) {
  const required = {
    FIREBASE_SERVICE_ACCOUNT: JSON.stringify(firebaseServiceAccount),
    FB_API_KEY: firebaseApiKey,
    WORKER_SHARED_SECRET: workerSharedSecret,
    GITHUB_TOKEN: githubToken,
    SCIM_TOKEN: scimToken,
    ALERT_WEBHOOK_URL: alertWebhookUrl,
  };
  const missing = Object.entries(required)
    .filter(([, value]) => !value)
    .map(([key]) => key);
  if (missing.length) throw new Error(`Missing tenant worker secrets: ${missing.join(', ')}`);
  return [
    '# Generated by tool/build_tenant_env.mjs — do not commit.',
    ...Object.entries(required).map(([key, value]) => `${key}=${escapeEnvValue(value)}`),
    `INGEST_SHARED_SECRET=${escapeEnvValue(ingestSharedSecret || workerSharedSecret)}`,
    'SCIM_DEFAULT_ROLE=supervisor',
    'SCIM_GRANTABLE_ROLES=supervisor,admin',
    'SCIM_DEFAULT_FACTORY=Usine A',
    '',
  ].join('\n');
}

function argValue(argv, key) {
  const index = argv.indexOf(`--${key}`);
  return index === -1 ? '' : argv[index + 1] || '';
}

async function main() {
  const argv = process.argv.slice(2);
  const runtimePath = argValue(argv, 'runtime-service-account');
  const webConfigPath = argValue(argv, 'firebase-web-config');
  const outputPath = argValue(argv, 'output');
  if (!runtimePath || !webConfigPath || !outputPath) {
    throw new Error(
      'Usage: node tool/build_tenant_env.mjs --runtime-service-account <json> ' +
      '--firebase-web-config <json> --output <.env.tenant>',
    );
  }
  const runtime = JSON.parse(readFileSync(runtimePath, 'utf8'));
  const web = JSON.parse(readFileSync(webConfigPath, 'utf8'));
  const contents = buildTenantEnv({
    firebaseServiceAccount: runtime,
    firebaseApiKey: web.apiKey,
    workerSharedSecret: process.env.WORKER_SHARED_SECRET || randomBytes(32).toString('base64url'),
    githubToken: process.env.SIAS_GITHUB_TOKEN,
    scimToken: process.env.SCIM_TOKEN || randomBytes(32).toString('base64url'),
    alertWebhookUrl: process.env.ALERT_WEBHOOK_URL,
    ingestSharedSecret: process.env.INGEST_SHARED_SECRET || randomBytes(32).toString('base64url'),
  });
  writeFileSync(outputPath, contents, { mode: 0o600 });
  console.log('Tenant worker secret bundle created (values redacted).');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(`Tenant env build failed: ${error.message}`);
    process.exitCode = 1;
  });
}
