-- SIAS B2B order control-plane schema.
-- Run in the private Supabase project used by sias-store.
-- The Store Worker uses only the service_role key; browsers never query these
-- tables directly.

create table if not exists public.sias_orders (
  id bigint generated by default as identity primary key,
  tenant_code text not null unique,
  company text not null,
  contact_name text not null,
  email text not null,
  phone text,
  country text,
  factories text not null default '1',
  plan text not null,
  billing text not null,
  currency text not null default 'USD',
  amount_display text,
  notes text,
  pm_name text,
  pm_email text,
  supervisor_name text,
  supervisor_email text,
  payment_method text not null default 'bank_transfer',
  full_package boolean not null default false,
  status text not null default 'under_review',
  confirmed_at timestamptz,
  paid_at timestamptz,
  provisioning_started_at timestamptz,
  provisioned_at timestamptz,
  app_url text,
  firebase_project_id text,
  provisioning_run_id text,
  provisioning_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sias_orders add column if not exists pm_name text;
alter table public.sias_orders add column if not exists pm_email text;
alter table public.sias_orders add column if not exists supervisor_name text;
alter table public.sias_orders add column if not exists supervisor_email text;
alter table public.sias_orders add column if not exists payment_method text not null default 'bank_transfer';
alter table public.sias_orders add column if not exists full_package boolean not null default false;
alter table public.sias_orders add column if not exists confirmed_at timestamptz;
alter table public.sias_orders add column if not exists paid_at timestamptz;
alter table public.sias_orders add column if not exists provisioning_started_at timestamptz;
alter table public.sias_orders add column if not exists provisioned_at timestamptz;
alter table public.sias_orders add column if not exists app_url text;
alter table public.sias_orders add column if not exists firebase_project_id text;
alter table public.sias_orders add column if not exists provisioning_run_id text;
alter table public.sias_orders add column if not exists provisioning_error text;
alter table public.sias_orders add column if not exists updated_at timestamptz not null default now();

-- Preserve the old dashboard's orders while moving them onto the explicit
-- Accept/Paid state machine.
update public.sias_orders
set status = 'under_review'
where status = 'awaiting_payment';

alter table public.sias_orders alter column status set default 'under_review';
alter table public.sias_orders drop constraint if exists sias_orders_status_check;
alter table public.sias_orders
  add constraint sias_orders_status_check check (
    status in (
      'under_review',
      'confirmed',
      'provisioning_queued',
      'provisioning',
      'active',
      'provisioning_failed',
      'rejected'
    )
  );

create index if not exists sias_orders_status_created_idx
  on public.sias_orders (status, created_at desc);

-- Older storefront migrations used the same definition under this name.
-- Keep one canonical index so the control plane stays easy to audit.
drop index if exists public.sias_orders_status_idx;

create table if not exists public.sias_order_events (
  id bigint generated by default as identity primary key,
  -- text keeps this migration compatible with deployments whose legacy order
  -- primary key is UUID rather than bigint.
  order_id text not null,
  event_type text not null,
  event_id text not null unique,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists sias_order_events_order_created_idx
  on public.sias_order_events (order_id, created_at desc);

create or replace function public.set_sias_order_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sias_orders_set_updated_at on public.sias_orders;
create trigger sias_orders_set_updated_at
before update on public.sias_orders
for each row execute function public.set_sias_order_updated_at();

alter table public.sias_orders enable row level security;
alter table public.sias_order_events enable row level security;

revoke all on table public.sias_orders from anon, authenticated;
revoke all on table public.sias_order_events from anon, authenticated;

comment on table public.sias_orders is
  'Private SIAS B2B order state machine. Accessed only by trusted service-role automation.';
comment on column public.sias_orders.status is
  'under_review -> confirmed -> provisioning_queued -> provisioning -> active; Paid may move directly from under_review.';
